# Generated by Django 4.2.1 on 2024-01-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userorders', '0006_alter_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_status',
            field=models.CharField(choices=[('canceled', 'canceled'), ('pending', 'pending'), ('delivered', 'delivered'), ('shipped', 'shipped')], default='pending', max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='payment_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
