# Generated by Django 4.2.1 on 2024-01-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userorders', '0007_remove_order_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_status',
            field=models.CharField(choices=[('shipped', 'shipped'), ('pending', 'pending'), ('delivered', 'delivered'), ('canceled', 'canceled')], default='pending', max_length=100),
        ),
    ]
