# Generated by Django 4.2.1 on 2024-01-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userorders', '0008_alter_orderitem_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_status',
            field=models.CharField(choices=[('shipped', 'shipped'), ('delivered', 'delivered'), ('canceled', 'canceled'), ('pending', 'pending')], default='pending', max_length=100),
        ),
    ]
